### ISSUE TITLE
Horaro/Oengus importer

### ISSUE THREAD

**Issue by riek-lt** [Indiethon/donation-tracker#2]
Import run info from both horaro and oengus

Note: Only difficult thing would be that names for columns in Horaro are differnt, so column selector? Or standardize them. Oengus is ezpz

**Comment by nicnacnic** [comment]
Oengus run importer is bug-free (for now) and in the latest build. I don't see many people using a Horaro import feature, and it's a lot more complicated than Oengus. For now Oengus works and maybe in the future I'll implement Horaro if people need it.
